# Global settings applied to the whole site.
[build]
  # base    = "site"
  publish = "build"
  command = "bin/build -e production"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = "bin/build -e production"

[context.staging]
  command = "bin/build -e staging"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  command = "bin/build -e review"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.branch-deploy]
  command = "bin/build -e review"

# Specific branch context: Deploys from this branch
# will take these settings and override their
# current ones.
[context.feature]
  command = "bin/build -e staging"
